# Site settings
title: Sebastian Hubenschmid | Personal Website
email: info@sebi.sh
description: Sebastian Hubenschmid, PostDoc at Aarhus University, Denmark
baseurl: ""
encoding: utf-8
url: "https://sebi.sh"
github_username:  SebiH

# Build settings
env: production
destination: _site/
markdown: kramdown

sass:
    style: compressed

collections:
  bib:
    output: true

exclude:
  - build.sh
  - README.md
  - vendor
