# Site settings
title: Sebastian Hubenschmid | Personal website
email: contact@sebi.sh
description: Sebastian Hubenschmid, CompScience Student (B.Sc.) and Software Engineer
baseurl: ""
url: "https://sebi.sh"
twitter_username: Sebi__H
github_username:  SebiH

# Build settings
env: production
destination: ../_site/
markdown: kramdown
gems:
    - jekyll-angular
    - jekyll_image_encode

