# Site settings
title: Sebastian Hubenschmid | Personal Website
email: info@sebi.sh
description: Sebastian Hubenschmid, Ph.D. student at the HCI Group, University of Konstanz, Germany
baseurl: ""
encoding: utf-8
url: "https://sebi.sh"
twitter_username: Sebi__H
github_username:  SebiH

# Build settings
env: production
destination: ../_site/
markdown: kramdown

sass:
    style: compressed
